import { NextResponse } from "next/server";
import pool from "@/lib/db";
import { getSession } from "@/lib/session";

// POST /api/workshops/:id/clone
// Duplicates a workshop and all its exercises with a fresh invite code and draft status.
export async function POST(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const session = await getSession();

  if (!session.userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  if (session.role !== "instructor") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const client = await pool.connect();
  try {
    await client.query("BEGIN");

    // Verify ownership
    const workshopResult = await client.query(
      "SELECT id, title, description, instructor_id FROM workshops WHERE id = $1",
      [id]
    );
    if (workshopResult.rows.length === 0) {
      await client.query("ROLLBACK");
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    const workshop = workshopResult.rows[0];
    if (workshop.instructor_id !== session.userId) {
      await client.query("ROLLBACK");
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    // Clone workshop (draft status, new invite code generated by default)
    const cloneResult = await client.query(
      `INSERT INTO workshops (title, description, instructor_id, status)
       VALUES ($1, $2, $3, 'draft')
       RETURNING *`,
      [`${workshop.title} (Copy)`, workshop.description, session.userId]
    );
    const cloned = cloneResult.rows[0];

    // Clone all exercises (preserve sort_order, rubric, model_config, weights, scheduling)
    await client.query(
      `INSERT INTO exercises (workshop_id, title, instructions, system_prompt, model_config, rubric, sort_order, criterion_weights, open_at, close_at)
       SELECT $1, title, instructions, system_prompt, model_config, rubric, sort_order, criterion_weights, open_at, close_at
       FROM exercises WHERE workshop_id = $2
       ORDER BY sort_order ASC`,
      [cloned.id, id]
    );

    await client.query("COMMIT");
    return NextResponse.json(cloned, { status: 201 });
  } catch (err) {
    await client.query("ROLLBACK");
    console.error("Workshop clone error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  } finally {
    client.release();
  }
}
